[params]
  env = "production"
  defaultTheme = "light"
  disableThemeToggle = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  mainSections = ["essays", "policy", "fiction", "theater"]

[params.profileMode]
  enabled = false